In [12]:
#Libraries
import pandas as pd
from sqlalchemy import create_engine
import datetime

# Extract

In [3]:
#Reading the Weekly Top 100 songs csv
hot_stuff = "hot_stuff_2.csv"
hot_stuff_df = pd.read_csv(hot_stuff)
hot_stuff_df.head()

,url,weekid,week_position,song,performer,songid,instance,previous_week_position,peak_position,weeks_on_chart
0,https://www.billboard.com/charts/hot-100/2019-...,12/28/2019,1,All I Want For Christmas Is You,Mariah Carey,All I Want For Christmas Is YouMariah Carey,9,1.0,1,35
1,https://www.billboard.com/charts/hot-100/2019-...,12/28/2019,2,Rockin' Around The Christmas Tree,Brenda Lee,Rockin' Around The Christmas TreeBrenda Lee,9,3.0,2,31
2,https://www.billboard.com/charts/hot-100/2019-...,12/28/2019,3,Circles,Post Malone,CirclesPost Malone,1,2.0,1,16
3,https://www.billboard.com/charts/hot-100/2019-...,12/28/2019,4,Roxanne,Arizona Zervas,RoxanneArizona Zervas,1,6.0,4,7
4,https://www.billboard.com/charts/hot-100/2019-...,12/28/2019,5,Futsal Shuffle 2020,Lil Uzi Vert,Futsal Shuffle 2020Lil Uzi Vert,1,NaN,5,1

In [5]:
#Reading the Top 50 songs on spootify csv
top_50 = "top50.csv"
top_50_df = pd.read_csv(top_50, encoding = "ISO-8859-1")
top_50_df.head()

,Unnamed: 0,Track.Name,Artist.Name,Genre,Beats.Per.Minute,Energy,Danceability,Loudness..dB..,Liveness,Valence.,Length.,Acousticness..,Speechiness.,Popularity
0,1,Se√±orita,Shawn Mendes,canadian pop,117,55,76,-6,8,75,191,4,3,79
1,2,China,Anuel AA,reggaeton flow,105,81,79,-4,8,61,302,8,9,92
2,3,boyfriend (with Social House),Ariana Grande,dance pop,190,80,40,-4,16,70,186,12,46,85
3,4,Beautiful People (feat. Khalid),Ed Sheeran,pop,93,65,64,-8,8,55,198,12,19,86
4,5,Goodbyes (Feat. Young Thug),Post Malone,dfw rap,150,65,58,-4,11,18,175,45,7,94

# Transformation

In [16]:
#Creating a filtered DataFrane from specific Columns
hot_col = ["weekid", "song", "week_position", "performer"]
hot_stuff_transformed = hot_stuff_df[hot_col].copy()

hot_stuff_transformed.head()

,weekid,song,week_position,performer
0,12/28/2019,All I Want For Christmas Is You,1,Mariah Carey
1,12/28/2019,Rockin' Around The Christmas Tree,2,Brenda Lee
2,12/28/2019,Circles,3,Post Malone
3,12/28/2019,Roxanne,4,Arizona Zervas
4,12/28/2019,Futsal Shuffle 2020,5,Lil Uzi Vert

In [18]:
#Converting the weekid Column to Datetime format
hot_stuff_transformed['weekid'] = pd.to_datetime(hot_stuff_transformed['weekid'], format='%m/%d/%Y')

hot_stuff_transformed.head()

      weekid                               song  week_position       performer
0 2019-12-28    All I Want For Christmas Is You              1    Mariah Carey
1 2019-12-28  Rockin' Around The Christmas Tree              2      Brenda Lee
2 2019-12-28                            Circles              3     Post Malone
3 2019-12-28                            Roxanne              4  Arizona Zervas
4 2019-12-28                Futsal Shuffle 2020              5    Lil Uzi Vert

In [20]:
start_date = "2019-01-05"
end_date  = "2019-12-28"
mask = (hot_stuff_transformed['weekid'] >= start_date) & (hot_stuff_transformed['weekid'] <= end_date)
hot_stuff_transformed = hot_stuff_transformed.loc[mask]
hot_stuff_transformed

,weekid,song,week_position,performer
0,2019-12-28,All I Want For Christmas Is You,1,Mariah Carey
1,2019-12-28,Rockin' Around The Christmas Tree,2,Brenda Lee
2,2019-12-28,Circles,3,Post Malone
3,2019-12-28,Roxanne,4,Arizona Zervas
4,2019-12-28,Futsal Shuffle 2020,5,Lil Uzi Vert
...,...,...,...,...
5195,2019-01-05,Last Shot,96,Kip Moore
5196,2019-01-05,Fine China,97,Future & Juice WRLD
5197,2019-01-05,Envy Me,98,Calboy
5198,2019-01-05,Lost In Japan,99,Shawn Mendes X Zedd
5199,2019-01-05,This Is It,100,Scotty McCreery

In [22]:
hot_stuff_transformed.set_index('weekid', inplace=True)
hot_stuff_transformed

,song,week_position,performer
weekid,,,
2019-12-28,All I Want For Christmas Is You,1,Mariah Carey
2019-12-28,Rockin' Around The Christmas Tree,2,Brenda Lee
2019-12-28,Circles,3,Post Malone
2019-12-28,Roxanne,4,Arizona Zervas
2019-12-28,Futsal Shuffle 2020,5,Lil Uzi Vert
...,...,...,...
2019-01-05,Last Shot,96,Kip Moore
2019-01-05,Fine China,97,Future & Juice WRLD
2019-01-05,Envy Me,98,Calboy
2019-01-05,Lost In Japan,99,Shawn Mendes X Zedd
2019-01-05,This Is It,100,Scotty McCreery